### ISSUE TITLE
Generate only the color utilities needed

### ISSUE THREAD

**Issue by aciccarello** [Teradata/covalent#1000]
#### Feature Request

The [`covalent-colors()`](https://github.com/Teradata/covalent/blob/develop/src/platform/core/common/styles/colors/_colors.scss) mixin should be able to generate a select collection of styles. Each class would likely have to be generated explicitly but for applications that stick to a consistent theme it shouldn't be too many.

#### What is the expected behavior?
A developer should be able to generate only the classes they need. This would likely be an alternate to the kitchen sink mixin. It could probably be used as the implementation to the existing mixin.

```scss
// Mixin usage
text-color("red", 700);        // would generate .tc-red-700
background-color("grey", 500); // would generate .bgc-grey-500
fill-color("yellow", 200);     // would generate .fill-yellow-200
```

#### What is the motivation / use case for changing the behavior?
Most applications only use a small fraction of the color classes currently generated. To reduce the size of the CSS bundle, the developer should be able to be more selective.

##### Other information

This is related to #999

**Comment by aciccarello** [comment]
For our application, I created the following mixin. It is slightly more verbose to use than I'd like because you can't interpolate variable names is sass but it works. The fill mixin would be very similar.

```scss
@mixin text-color($colorName, $colorPalette, $hue: '') {
  @if ($hue == '') {
    .tc-#{$colorName} {
      color: mat-color($colorPalette) !important;
    }
  } @else {
    .tc-#{$colorName}-#{$hue} {
      color: mat-color($colorPalette, $hue) !important;
    }
  }
}
@mixin background-color($colorName, $colorPalette, $hue: '') {
  @if ($hue == '') {
    .bgc-#{$colorName} {
      background-color: mat-color($colorPalette) !important;
    }
  } @else {
    .bgc-#{$colorName}-#{$hue} {
      background-color: mat-color($colorPalette, $hue) !important;
    }
  }
}

// usage
.tc-white { color: rgba(white, 0.7) !important; } // white utilities are different
@include text-color('light-blue', $mat-light-blue, 700);
@include text-color('grey', $mat-grey, 600);
@include text-color('red', $mat-red, 200);
@include text-color('red', $mat-red, 600);
@include text-color('orange', $mat-orange, 500);
@include background-color('light-blue', $mat-light-blue, 100);
@include background-color('light-blue', $mat-light-blue, 700);
@include background-color('grey', $mat-grey, 700);
```
